create schema if not exists core;
create schema if not exists analytics;
create schema if not exists robovet;

do $$
begin
  -- Core tables
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'email_verifications')
     and not exists (select 1 from information_schema.tables where table_schema = 'core' and table_name = 'email_verifications') then
    alter table public.email_verifications set schema core;
  end if;

  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'users')
     and not exists (select 1 from information_schema.tables where table_schema = 'core' and table_name = 'users') then
    alter table public.users set schema core;
  end if;

  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'hospitals')
     and not exists (select 1 from information_schema.tables where table_schema = 'core' and table_name = 'hospitals') then
    alter table public.hospitals set schema core;
  end if;

  -- Analytics tables/views
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'analytics_daily_metrics'
  )
  and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'analytics'
      and table_name = 'analytics_daily_metrics'
  ) then
    alter table public.analytics_daily_metrics set schema analytics;
  end if;

  if exists (
    select 1
    from information_schema.views
    where table_schema = 'public'
      and table_name = 'analytics_daily_metrics_daily_view'
  )
  and not exists (
    select 1
    from information_schema.views
    where table_schema = 'analytics'
      and table_name = 'analytics_daily_metrics_daily_view'
  ) then
    alter view public.analytics_daily_metrics_daily_view set schema analytics;
  end if;
end $$;

-- Grants by schema ownership
grant usage on schema core to service_role, authenticated, anon;
grant usage on schema analytics to service_role, authenticated, anon;
grant usage on schema robovet to service_role;

grant select on table core.hospitals to service_role, authenticated, anon;
grant select on table core.users to service_role, authenticated;
grant select, insert, update on table analytics.analytics_daily_metrics to service_role;
grant select on table analytics.analytics_daily_metrics_daily_view to service_role, authenticated;
grant select, insert, update on table analytics.analytics_blog_daily_metrics to service_role;
grant select on table analytics.analytics_blog_daily_metrics to service_role, authenticated;
grant select, insert, update on table analytics.analytics_smartplace_daily_metrics to service_role;
grant select on table analytics.analytics_smartplace_daily_metrics to service_role, authenticated;

grant all privileges on all tables in schema robovet to service_role;

create table if not exists analytics.analytics_daily_metrics (
  account_id text not null,
  hospital_id text,
  hospital_name text,
  source text not null,
  metric_date date not null,
  metric_key text not null,
  metric_value numeric,
  metadata jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (account_id, source, metric_date, metric_key)
);

-- Blog admin stats (views/unique visitors) - separated table
create table if not exists analytics.analytics_blog_daily_metrics (
  account_id text not null,
  hospital_id text,
  hospital_name text,
  metric_date date not null,
  blog_views bigint,
  blog_unique_visitors bigint,
  metadata jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (account_id, metric_date)
);

-- SmartPlace stats (inflow) - separated table
create table if not exists analytics.analytics_smartplace_daily_metrics (
  account_id text not null,
  hospital_id text,
  hospital_name text,
  metric_date date not null,
  smartplace_inflow bigint,
  metadata jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (account_id, metric_date)
);

create table if not exists analytics.analytics_blog_keyword_ranks (
  account_id text not null,
  hospital_id text,
  hospital_name text,
  source text not null default 'blog',
  metric_date date not null,
  metric_key text not null,
  keyword text not null,
  section text not null,
  rank_value integer,
  exposed_url text,
  metadata jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (account_id, metric_date, keyword, section, metric_key)
);

create table if not exists analytics.analytics_blog_keyword_targets (
  id bigint generated by default as identity primary key,
  account_id text not null,
  hospital_id text,
  keyword text not null,
  is_active boolean not null default true,
  source text not null default 'manual',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, keyword)
);

create table if not exists analytics.analytics_searchad_accounts (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  customer_id text not null,
  api_license text not null,
  secret_key_encrypted text not null,
  is_active boolean not null default true,
  last_synced_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, customer_id)
);

create table if not exists analytics.analytics_searchad_daily_metrics (
  metric_date date not null,
  hospital_id text not null,
  customer_id text not null,
  campaign_id text not null default '',
  campaign_name text,
  adgroup_id text not null default '',
  adgroup_name text,
  keyword_id text not null default '',
  impressions bigint,
  clicks bigint,
  cost numeric,
  conversions numeric,
  conversion_value numeric,
  raw_payload jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (metric_date, customer_id, campaign_id, adgroup_id, keyword_id)
);

create table if not exists analytics.analytics_place_keyword_ranks (
  metric_date date not null,
  hospital_id text,
  keyword text not null,
  store_name text not null,
  section text not null default '플레이스',
  metric_key text not null default 'place_rank_integrated',
  rank_value integer,
  metadata jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (metric_date, keyword, store_name, section, metric_key)
);

create table if not exists analytics.analytics_place_keyword_targets (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  keyword text not null,
  is_active boolean not null default true,
  source text not null default 'manual',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, keyword)
);

create table if not exists analytics.chart_upload_runs (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  source_file_name text not null,
  source_file_hash text not null,
  status text not null default 'pending',
  total_rows integer not null default 0,
  imported_rows integer not null default 0,
  skipped_rows integer not null default 0,
  error_rows integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  unique (hospital_id, chart_type, source_file_hash)
);

create table if not exists analytics.chart_transactions_raw (
  id bigint generated by default as identity primary key,
  run_id bigint references analytics.chart_upload_runs(id) on delete set null,
  hospital_id text not null,
  chart_type text not null,
  source_file_name text not null,
  source_file_hash text not null,
  source_row_no integer not null,
  row_signature text not null,
  service_date date not null,
  customer_no_raw text,
  customer_name_raw text,
  patient_name_raw text,
  receipt_no_raw text,
  treatment_content_raw text,
  bill_no_raw text,
  final_amount_raw numeric not null default 0,
  customer_key_norm text not null,
  patient_key_norm text not null,
  dedupe_key text,
  raw_payload jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  unique (hospital_id, chart_type, source_file_hash, source_row_no),
  unique (hospital_id, chart_type, row_signature),
  unique (hospital_id, chart_type, dedupe_key)
);

create table if not exists analytics.chart_patient_master (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  patient_key_norm text not null,
  customer_key_norm text,
  patient_name_latest text,
  customer_name_latest text,
  first_visit_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, chart_type, patient_key_norm)
);

create table if not exists analytics.chart_daily_kpis (
  metric_date date not null,
  hospital_id text not null,
  chart_type text not null,
  sales_amount numeric not null default 0,
  visit_count integer not null default 0,
  new_patient_count integer not null default 0,
  source_run_id bigint references analytics.chart_upload_runs(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (metric_date, hospital_id, chart_type)
);

create table if not exists analytics.chart_upload_errors (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analytics.chart_upload_runs(id) on delete cascade,
  hospital_id text not null,
  chart_type text not null,
  source_row_no integer,
  error_code text,
  error_message text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_blog_keyword_targets_active
  on analytics.analytics_blog_keyword_targets (is_active, account_id, keyword);

create or replace function analytics.blog_keyword_targets_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function analytics.chart_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_blog_keyword_targets_updated_at on analytics.analytics_blog_keyword_targets;
create trigger trg_blog_keyword_targets_updated_at
  before update on analytics.analytics_blog_keyword_targets
  for each row
  execute function analytics.blog_keyword_targets_touch_updated_at();

drop trigger if exists trg_searchad_accounts_updated_at on analytics.analytics_searchad_accounts;
create trigger trg_searchad_accounts_updated_at
  before update on analytics.analytics_searchad_accounts
  for each row
  execute function analytics.blog_keyword_targets_touch_updated_at();

drop trigger if exists trg_place_keyword_targets_updated_at on analytics.analytics_place_keyword_targets;
create trigger trg_place_keyword_targets_updated_at
  before update on analytics.analytics_place_keyword_targets
  for each row
  execute function analytics.blog_keyword_targets_touch_updated_at();

drop trigger if exists trg_chart_patient_master_updated_at on analytics.chart_patient_master;
create trigger trg_chart_patient_master_updated_at
  before update on analytics.chart_patient_master
  for each row
  execute function analytics.chart_touch_updated_at();

drop trigger if exists trg_chart_daily_kpis_updated_at on analytics.chart_daily_kpis;
create trigger trg_chart_daily_kpis_updated_at
  before update on analytics.chart_daily_kpis
  for each row
  execute function analytics.chart_touch_updated_at();

alter table if exists core.hospitals
  add column if not exists naver_blog_id text;

alter table if exists core.hospitals
  add column if not exists smartplace_stat_url text;

alter table if exists core.hospitals
  add column if not exists debug_port integer;

alter table if exists core.hospitals
  add column if not exists searchad_customer_id text;

alter table if exists core.hospitals
  add column if not exists searchad_api_license text;

alter table if exists core.hospitals
  add column if not exists searchad_secret_key_encrypted text;

alter table if exists core.hospitals
  add column if not exists searchad_is_active boolean not null default false;

alter table if exists core.hospitals
  add column if not exists searchad_last_synced_at timestamptz;

alter table if exists core.hospitals
  add column if not exists googleads_customer_id text;

alter table if exists core.hospitals
  add column if not exists googleads_refresh_token_encrypted text;

alter table if exists core.hospitals
  add column if not exists googleads_is_active boolean not null default false;

alter table if exists core.hospitals
  add column if not exists googleads_last_synced_at timestamptz;

alter table if exists core.hospitals
  add column if not exists googleads_metadata jsonb not null default '{}'::jsonb;

create unique index if not exists uq_hospitals_naver_blog_id
  on core.hospitals (naver_blog_id)
  where naver_blog_id is not null;

create unique index if not exists uq_hospitals_searchad_customer_id
  on core.hospitals (searchad_customer_id)
  where searchad_customer_id is not null;

create unique index if not exists uq_hospitals_googleads_customer_id
  on core.hospitals (googleads_customer_id)
  where googleads_customer_id is not null;

alter table if exists core.users
  add column if not exists role text not null default 'member';

alter table if exists core.users
  add column if not exists hospital_id text;

create index if not exists idx_core_users_hospital
  on core.users (hospital_id);

create table if not exists core.platform_users (
  id text primary key,
  email text,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_platform_users_email_lower
  on core.platform_users (lower(email));

create index if not exists idx_analytics_daily_metrics_account_date
  on analytics.analytics_daily_metrics (account_id, metric_date desc);

create index if not exists idx_analytics_daily_metrics_hospital_date
  on analytics.analytics_daily_metrics (hospital_id, metric_date desc);

create index if not exists idx_blog_keyword_ranks_hospital_date
  on analytics.analytics_blog_keyword_ranks (hospital_id, metric_date desc);

create index if not exists idx_blog_keyword_ranks_keyword_date
  on analytics.analytics_blog_keyword_ranks (keyword, metric_date desc);

create index if not exists idx_searchad_accounts_active
  on analytics.analytics_searchad_accounts (is_active, hospital_id, customer_id);

create index if not exists idx_searchad_daily_metrics_hospital_date
  on analytics.analytics_searchad_daily_metrics (hospital_id, metric_date desc);

create index if not exists idx_searchad_daily_metrics_customer_date
  on analytics.analytics_searchad_daily_metrics (customer_id, metric_date desc);

create index if not exists idx_place_keyword_ranks_metric_date
  on analytics.analytics_place_keyword_ranks (metric_date desc, keyword, store_name);

create index if not exists idx_place_keyword_targets_active
  on analytics.analytics_place_keyword_targets (is_active, hospital_id, keyword);

create index if not exists idx_chart_upload_runs_hospital_started_at
  on analytics.chart_upload_runs (hospital_id, started_at desc);

create index if not exists idx_chart_transactions_raw_hospital_service_date
  on analytics.chart_transactions_raw (hospital_id, service_date desc);

create index if not exists idx_chart_transactions_raw_patient_key
  on analytics.chart_transactions_raw (hospital_id, chart_type, patient_key_norm);

create index if not exists idx_chart_patient_master_first_visit
  on analytics.chart_patient_master (hospital_id, chart_type, first_visit_date desc);

create index if not exists idx_chart_daily_kpis_hospital_metric_date
  on analytics.chart_daily_kpis (hospital_id, metric_date desc);

create index if not exists idx_chart_upload_errors_run
  on analytics.chart_upload_errors (run_id, created_at desc);

create or replace view analytics.analytics_daily_metrics_daily_view as
select
  m.metric_date,
  m.hospital_id,
  coalesce(max(m.hospital_name), max(h.name)) as hospital_name,
  m.account_id,
  max(case when m.metric_key = 'blog_views' then m.metric_value end) as blog_views,
  max(case when m.metric_key = 'blog_unique_visitors' then m.metric_value end) as blog_unique_visitors,
  max(case when m.metric_key = 'smartplace_inflow' then m.metric_value end) as smartplace_inflow,
  max(m.collected_at) as last_collected_at
from analytics.analytics_daily_metrics m
left join core.hospitals h
  on h.id::text = m.hospital_id
group by
  m.metric_date,
  m.hospital_id,
  m.account_id;

create or replace view analytics.analytics_blog_keyword_ranks_daily_view as
select
  r.metric_date,
  r.hospital_id,
  coalesce(max(r.hospital_name), max(h.name)) as hospital_name,
  r.account_id,
  r.keyword,
  max(case when r.metric_key = 'blog_rank_integrated' then r.rank_value end) as blog_rank_integrated,
  max(case when r.metric_key = 'blog_rank_pet_popular' then r.rank_value end) as blog_rank_pet_popular,
  max(case when r.metric_key = 'blog_rank_general' then r.rank_value end) as blog_rank_general,
  max(case when r.metric_key = 'blog_rank_tab' then r.rank_value end) as blog_rank_tab,
  min(r.rank_value) filter (where r.rank_value is not null) as blog_rank_best,
  max(r.collected_at) as last_collected_at
from analytics.analytics_blog_keyword_ranks r
left join core.hospitals h
  on h.id::text = r.hospital_id
group by
  r.metric_date,
  r.hospital_id,
  r.account_id,
  r.keyword;

create or replace view analytics.chart_kpis_period_view as
select
  date_trunc('week', metric_date)::date as period_start_date,
  'week'::text as period_type,
  hospital_id,
  chart_type,
  sum(sales_amount) as sales_amount,
  sum(visit_count) as visit_count,
  sum(new_patient_count) as new_patient_count
from analytics.chart_daily_kpis
group by 1, 2, 3, 4
union all
select
  date_trunc('month', metric_date)::date as period_start_date,
  'month'::text as period_type,
  hospital_id,
  chart_type,
  sum(sales_amount) as sales_amount,
  sum(visit_count) as visit_count,
  sum(new_patient_count) as new_patient_count
from analytics.chart_daily_kpis
group by 1, 2, 3, 4
union all
select
  metric_date as period_start_date,
  'day'::text as period_type,
  hospital_id,
  chart_type,
  sales_amount,
  visit_count,
  new_patient_count
from analytics.chart_daily_kpis;

grant select, insert, update on table analytics.analytics_blog_keyword_ranks to service_role;
grant select on table analytics.analytics_blog_keyword_ranks_daily_view to service_role, authenticated;
grant select, insert, update, delete on table analytics.analytics_blog_keyword_targets to service_role;
grant select, insert, update, delete on table analytics.analytics_blog_keyword_targets to authenticated;
grant select, insert, update, delete on table analytics.analytics_searchad_accounts to service_role;
grant select, insert, update on table analytics.analytics_searchad_daily_metrics to service_role;
grant select on table analytics.analytics_searchad_accounts to authenticated;
grant select on table analytics.analytics_searchad_daily_metrics to authenticated;
grant select, insert, update on table analytics.analytics_place_keyword_ranks to service_role;
grant select on table analytics.analytics_place_keyword_ranks to authenticated;
grant select, insert, update, delete on table analytics.analytics_place_keyword_targets to service_role;
grant select, insert, update, delete on table analytics.analytics_place_keyword_targets to authenticated;
grant select, insert, update, delete on table analytics.chart_upload_runs to service_role;
grant select, insert, update, delete on table analytics.chart_transactions_raw to service_role;
grant select, insert, update, delete on table analytics.chart_patient_master to service_role;
grant select, insert, update, delete on table analytics.chart_daily_kpis to service_role;
grant select, insert, update, delete on table analytics.chart_upload_errors to service_role;
grant select on table analytics.chart_daily_kpis to authenticated;
grant select on table analytics.chart_patient_master to authenticated;
grant select on table analytics.chart_kpis_period_view to authenticated, service_role;

alter table core.users enable row level security;
alter table analytics.analytics_daily_metrics enable row level security;
alter table analytics.analytics_blog_daily_metrics enable row level security;
alter table analytics.analytics_smartplace_daily_metrics enable row level security;
alter table analytics.analytics_blog_keyword_ranks enable row level security;
alter table analytics.analytics_blog_keyword_targets enable row level security;
alter table analytics.analytics_searchad_accounts enable row level security;
alter table analytics.analytics_searchad_daily_metrics enable row level security;
alter table analytics.analytics_place_keyword_ranks enable row level security;
alter table analytics.analytics_place_keyword_targets enable row level security;
alter table analytics.chart_upload_runs enable row level security;
alter table analytics.chart_transactions_raw enable row level security;
alter table analytics.chart_patient_master enable row level security;
alter table analytics.chart_daily_kpis enable row level security;
alter table analytics.chart_upload_errors enable row level security;

drop policy if exists "users_select_own" on core.users;
create policy "users_select_own"
  on core.users
  for select
  to authenticated
  using (id::text = auth.uid()::text);

drop policy if exists "metrics_select_assigned_hospitals" on analytics.analytics_daily_metrics;
create policy "metrics_select_assigned_hospitals"
  on analytics.analytics_daily_metrics
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_daily_metrics.hospital_id
        )
    )
  );

drop policy if exists "blog_daily_metrics_select_assigned_hospitals" on analytics.analytics_blog_daily_metrics;
create policy "blog_daily_metrics_select_assigned_hospitals"
  on analytics.analytics_blog_daily_metrics
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_blog_daily_metrics.hospital_id
        )
    )
  );

drop policy if exists "smartplace_daily_metrics_select_assigned_hospitals" on analytics.analytics_smartplace_daily_metrics;
create policy "smartplace_daily_metrics_select_assigned_hospitals"
  on analytics.analytics_smartplace_daily_metrics
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_smartplace_daily_metrics.hospital_id
        )
    )
  );

drop policy if exists "blog_keyword_ranks_select_assigned_hospitals" on analytics.analytics_blog_keyword_ranks;
create policy "blog_keyword_ranks_select_assigned_hospitals"
  on analytics.analytics_blog_keyword_ranks
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_blog_keyword_ranks.hospital_id
        )
    )
  );

drop policy if exists "blog_keyword_targets_select_assigned_hospitals" on analytics.analytics_blog_keyword_targets;
create policy "blog_keyword_targets_select_assigned_hospitals"
  on analytics.analytics_blog_keyword_targets
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_blog_keyword_targets.hospital_id
        )
    )
  );

drop policy if exists "blog_keyword_targets_insert_assigned_hospitals" on analytics.analytics_blog_keyword_targets;
create policy "blog_keyword_targets_insert_assigned_hospitals"
  on analytics.analytics_blog_keyword_targets
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            u.hospital_id is not null
            and u.hospital_id = analytics_blog_keyword_targets.hospital_id
          )
        )
    )
  );

drop policy if exists "blog_keyword_targets_update_assigned_hospitals" on analytics.analytics_blog_keyword_targets;
create policy "blog_keyword_targets_update_assigned_hospitals"
  on analytics.analytics_blog_keyword_targets
  for update
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_blog_keyword_targets.hospital_id
        )
    )
  )
  with check (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            u.hospital_id is not null
            and u.hospital_id = analytics_blog_keyword_targets.hospital_id
          )
        )
    )
  );

drop policy if exists "blog_keyword_targets_delete_assigned_hospitals" on analytics.analytics_blog_keyword_targets;
create policy "blog_keyword_targets_delete_assigned_hospitals"
  on analytics.analytics_blog_keyword_targets
  for delete
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_blog_keyword_targets.hospital_id
        )
    )
  );

drop policy if exists "searchad_accounts_select_assigned_hospitals" on analytics.analytics_searchad_accounts;
create policy "searchad_accounts_select_assigned_hospitals"
  on analytics.analytics_searchad_accounts
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_searchad_accounts.hospital_id
        )
    )
  );

drop policy if exists "searchad_daily_metrics_select_assigned_hospitals" on analytics.analytics_searchad_daily_metrics;
create policy "searchad_daily_metrics_select_assigned_hospitals"
  on analytics.analytics_searchad_daily_metrics
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_searchad_daily_metrics.hospital_id
        )
    )
  );

drop policy if exists "place_keyword_ranks_select_assigned_hospitals" on analytics.analytics_place_keyword_ranks;
create policy "place_keyword_ranks_select_assigned_hospitals"
  on analytics.analytics_place_keyword_ranks
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            analytics_place_keyword_ranks.hospital_id is not null
            and u.hospital_id = analytics_place_keyword_ranks.hospital_id
          )
        )
    )
  );

drop policy if exists "place_keyword_targets_select_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_select_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_place_keyword_targets.hospital_id
        )
    )
  );

drop policy if exists "place_keyword_targets_insert_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_insert_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            u.hospital_id is not null
            and u.hospital_id = analytics_place_keyword_targets.hospital_id
          )
        )
    )
  );

drop policy if exists "place_keyword_targets_update_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_update_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for update
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_place_keyword_targets.hospital_id
        )
    )
  )
  with check (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            u.hospital_id is not null
            and u.hospital_id = analytics_place_keyword_targets.hospital_id
          )
        )
    )
  );

drop policy if exists "place_keyword_targets_delete_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_delete_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for delete
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_place_keyword_targets.hospital_id
        )
    )
  );

drop policy if exists "chart_daily_kpis_select_assigned_hospitals" on analytics.chart_daily_kpis;
create policy "chart_daily_kpis_select_assigned_hospitals"
  on analytics.chart_daily_kpis
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_daily_kpis.hospital_id
        )
    )
  );

drop policy if exists "chart_patient_master_select_assigned_hospitals" on analytics.chart_patient_master;
create policy "chart_patient_master_select_assigned_hospitals"
  on analytics.chart_patient_master
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_patient_master.hospital_id
        )
    )
  );

do $$
declare
  t record;
begin
  -- Everything else in public => robovet
  for t in
    select tablename
    from pg_tables
    where schemaname = 'public'
      and tablename not in ('email_verifications', 'hospitals', 'users', 'analytics_daily_metrics', 'spatial_ref_sys')
  loop
    -- Skip move when same table already exists in robovet.
    if exists (
      select 1
      from pg_tables
      where schemaname = 'robovet'
        and tablename = t.tablename
    ) then
      raise notice 'skip moving public.% to robovet (already exists)', t.tablename;
    else
      execute format('alter table public.%I set schema robovet', t.tablename);
    end if;
  end loop;
end $$;
