export const HEALTH_CHECKUP_MAX_OVERALL_CHARS = 1200;
export const HEALTH_CHECKUP_MAX_FOLLOW_UP_CHARS = 1000;
export const HEALTH_CHECKUP_MIN_OVERALL_CHARS = 300;
export const HEALTH_CHECKUP_MIN_FOLLOW_UP_CHARS = 300;

export const HEALTH_CHECKUP_MAX_RECHECK_TITLE_CHARS = 15;
export const HEALTH_CHECKUP_MAX_RECHECK_BODY_CHARS = 50;

export const HEALTH_CHECKUP_PROMPT_MIN_OVERALL_CHARS = 300;
export const HEALTH_CHECKUP_PROMPT_MAX_OVERALL_CHARS = 1200;
export const HEALTH_CHECKUP_PROMPT_MIN_FOLLOW_UP_CHARS = 300;
export const HEALTH_CHECKUP_PROMPT_MAX_FOLLOW_UP_CHARS = 1000;
export const HEALTH_CHECKUP_PROMPT_SYSTEMS_DX_MAX_CHARS = 320;
export const HEALTH_CHECKUP_PROMPT_SYSTEMS_IMP_MAX_CHARS = 320;
export const HEALTH_CHECKUP_PROMPT_DENTAL_SKIN_DX_MAX_CHARS = 280;
export const HEALTH_CHECKUP_PROMPT_DENTAL_SKIN_IMP_MAX_CHARS = 280;
export const HEALTH_CHECKUP_PROMPT_IMAGING_INTERP_MAX_CHARS = 180;
export const HEALTH_CHECKUP_PROMPT_LAB_INTERP_MAX_CHARS = 230;
