-- Google Ads: account mapping + daily metrics tables (idempotent)

create schema if not exists analytics;

create table if not exists analytics.analytics_googleads_accounts (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  customer_id text not null,
  refresh_token_encrypted text,
  is_active boolean not null default true,
  last_synced_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, customer_id)
);

create table if not exists analytics.analytics_googleads_daily_metrics (
  metric_date date not null,
  hospital_id text not null,
  customer_id text not null,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  cost_micros bigint not null default 0,
  raw_payload jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (metric_date, hospital_id, customer_id)
);

-- Reuse updated_at trigger helper if present; otherwise create a local one.
create or replace function analytics.googleads_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_googleads_accounts_updated_at on analytics.analytics_googleads_accounts;
create trigger trg_googleads_accounts_updated_at
  before update on analytics.analytics_googleads_accounts
  for each row
  execute function analytics.googleads_touch_updated_at();

create index if not exists idx_googleads_accounts_active
  on analytics.analytics_googleads_accounts (is_active, hospital_id, customer_id);

create index if not exists idx_googleads_daily_metrics_hospital_date
  on analytics.analytics_googleads_daily_metrics (hospital_id, metric_date desc);

create index if not exists idx_googleads_daily_metrics_customer_date
  on analytics.analytics_googleads_daily_metrics (customer_id, metric_date desc);

grant select, insert, update, delete on table analytics.analytics_googleads_accounts to service_role;
grant select, insert, update on table analytics.analytics_googleads_daily_metrics to service_role;
grant select on table analytics.analytics_googleads_accounts to authenticated;
grant select on table analytics.analytics_googleads_daily_metrics to authenticated;

alter table analytics.analytics_googleads_accounts enable row level security;
alter table analytics.analytics_googleads_daily_metrics enable row level security;

drop policy if exists "googleads_accounts_select_assigned_hospitals" on analytics.analytics_googleads_accounts;
create policy "googleads_accounts_select_assigned_hospitals"
  on analytics.analytics_googleads_accounts
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_googleads_accounts.hospital_id
        )
    )
  );

drop policy if exists "googleads_daily_metrics_select_assigned_hospitals" on analytics.analytics_googleads_daily_metrics;
create policy "googleads_daily_metrics_select_assigned_hospitals"
  on analytics.analytics_googleads_daily_metrics
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_googleads_daily_metrics.hospital_id
        )
    )
  );

