-- Incremental migration: place keyword DB input targets

create schema if not exists analytics;

create table if not exists analytics.analytics_place_keyword_targets (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  keyword text not null,
  is_active boolean not null default true,
  priority integer not null default 100,
  source text not null default 'manual',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, keyword)
);

create or replace function analytics.blog_keyword_targets_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_place_keyword_targets_updated_at on analytics.analytics_place_keyword_targets;
create trigger trg_place_keyword_targets_updated_at
  before update on analytics.analytics_place_keyword_targets
  for each row
  execute function analytics.blog_keyword_targets_touch_updated_at();

create index if not exists idx_place_keyword_targets_active
  on analytics.analytics_place_keyword_targets (is_active, hospital_id, priority, keyword);

grant select, insert, update, delete on table analytics.analytics_place_keyword_targets to service_role;
grant select, insert, update, delete on table analytics.analytics_place_keyword_targets to authenticated;

alter table analytics.analytics_place_keyword_targets enable row level security;

drop policy if exists "place_keyword_targets_select_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_select_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_place_keyword_targets.hospital_id
        )
    )
  );

drop policy if exists "place_keyword_targets_insert_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_insert_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            u.hospital_id is not null
            and u.hospital_id = analytics_place_keyword_targets.hospital_id
          )
        )
    )
  );

drop policy if exists "place_keyword_targets_update_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_update_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for update
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_place_keyword_targets.hospital_id
        )
    )
  )
  with check (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or (
            u.hospital_id is not null
            and u.hospital_id = analytics_place_keyword_targets.hospital_id
          )
        )
    )
  );

drop policy if exists "place_keyword_targets_delete_assigned_hospitals" on analytics.analytics_place_keyword_targets;
create policy "place_keyword_targets_delete_assigned_hospitals"
  on analytics.analytics_place_keyword_targets
  for delete
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_place_keyword_targets.hospital_id
        )
    )
  );
