-- Incremental migration (idempotent): SearchAd account mapping + daily metrics tables

create schema if not exists analytics;

create table if not exists analytics.analytics_searchad_accounts (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  customer_id text not null,
  api_license text not null,
  secret_key_encrypted text not null,
  is_active boolean not null default true,
  last_synced_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, customer_id)
);

create table if not exists analytics.analytics_searchad_daily_metrics (
  metric_date date not null,
  hospital_id text not null,
  customer_id text not null,
  campaign_id text not null default '',
  adgroup_id text not null default '',
  keyword_id text not null default '',
  impressions bigint,
  clicks bigint,
  cost numeric,
  conversions numeric,
  conversion_value numeric,
  raw_payload jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now(),
  primary key (metric_date, customer_id, campaign_id, adgroup_id, keyword_id)
);

create or replace function analytics.blog_keyword_targets_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_searchad_accounts_updated_at on analytics.analytics_searchad_accounts;
create trigger trg_searchad_accounts_updated_at
  before update on analytics.analytics_searchad_accounts
  for each row
  execute function analytics.blog_keyword_targets_touch_updated_at();

create index if not exists idx_searchad_accounts_active
  on analytics.analytics_searchad_accounts (is_active, hospital_id, customer_id);

create index if not exists idx_searchad_daily_metrics_hospital_date
  on analytics.analytics_searchad_daily_metrics (hospital_id, metric_date desc);

create index if not exists idx_searchad_daily_metrics_customer_date
  on analytics.analytics_searchad_daily_metrics (customer_id, metric_date desc);

grant select, insert, update, delete on table analytics.analytics_searchad_accounts to service_role;
grant select, insert, update on table analytics.analytics_searchad_daily_metrics to service_role;
grant select on table analytics.analytics_searchad_accounts to authenticated;
grant select on table analytics.analytics_searchad_daily_metrics to authenticated;

alter table analytics.analytics_searchad_accounts enable row level security;
alter table analytics.analytics_searchad_daily_metrics enable row level security;

drop policy if exists "searchad_accounts_select_assigned_hospitals" on analytics.analytics_searchad_accounts;
create policy "searchad_accounts_select_assigned_hospitals"
  on analytics.analytics_searchad_accounts
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_searchad_accounts.hospital_id
        )
    )
  );

drop policy if exists "searchad_daily_metrics_select_assigned_hospitals" on analytics.analytics_searchad_daily_metrics;
create policy "searchad_daily_metrics_select_assigned_hospitals"
  on analytics.analytics_searchad_daily_metrics
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = analytics_searchad_daily_metrics.hospital_id
        )
    )
  );
