-- Align existing chart ingestion schema to customer-centric model.

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'analytics' and table_name = 'chart_patient_master'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'analytics' and table_name = 'chart_customer_master'
  ) then
    execute 'alter table analytics.chart_patient_master rename to chart_customer_master';
  end if;
end $$;

alter table if exists analytics.chart_customer_master
  add column if not exists customer_no_raw_latest text;

alter table if exists analytics.chart_customer_master
  drop column if exists patient_name_latest;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'analytics'
      and table_name = 'chart_customer_master'
      and column_name = 'patient_key_norm'
  ) then
    execute 'alter table analytics.chart_customer_master drop constraint if exists chart_patient_master_hospital_id_chart_type_patient_key_norm_key';
    execute 'alter table analytics.chart_customer_master drop constraint if exists chart_customer_master_hospital_id_chart_type_patient_key_norm_key';
    execute 'alter table analytics.chart_customer_master drop column patient_key_norm';
  end if;
end $$;

-- KPI column: rename legacy new_patient_count -> new_customer_count, or add if missing.
do $$
begin
  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'analytics' and table_name = 'chart_daily_kpis'
  ) then
    return;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'analytics'
      and table_name = 'chart_daily_kpis'
      and column_name = 'new_customer_count'
  ) then
    return;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'analytics'
      and table_name = 'chart_daily_kpis'
      and column_name = 'new_patient_count'
  ) then
    execute 'alter table analytics.chart_daily_kpis rename column new_patient_count to new_customer_count';
  else
    execute 'alter table analytics.chart_daily_kpis add column new_customer_count integer not null default 0';
  end if;
end $$;

create table if not exists analytics.chart_customer_patients (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  customer_key_norm text not null,
  patient_key_norm text not null,
  patient_name_latest text,
  first_seen_date date not null,
  last_seen_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, chart_type, customer_key_norm, patient_key_norm)
);

create index if not exists idx_chart_customer_master_first_visit
  on analytics.chart_customer_master (hospital_id, chart_type, first_visit_date desc);

create index if not exists idx_chart_customer_patients_customer
  on analytics.chart_customer_patients (hospital_id, chart_type, customer_key_norm);

create or replace function analytics.chart_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_chart_customer_master_updated_at on analytics.chart_customer_master;
create trigger trg_chart_customer_master_updated_at
  before update on analytics.chart_customer_master
  for each row
  execute function analytics.chart_touch_updated_at();

drop trigger if exists trg_chart_customer_patients_updated_at on analytics.chart_customer_patients;
create trigger trg_chart_customer_patients_updated_at
  before update on analytics.chart_customer_patients
  for each row
  execute function analytics.chart_touch_updated_at();

drop trigger if exists trg_chart_daily_kpis_updated_at on analytics.chart_daily_kpis;
create trigger trg_chart_daily_kpis_updated_at
  before update on analytics.chart_daily_kpis
  for each row
  execute function analytics.chart_touch_updated_at();

grant select, insert, update, delete on table analytics.chart_customer_master to service_role;
grant select, insert, update, delete on table analytics.chart_customer_patients to service_role;
grant select on table analytics.chart_customer_master to authenticated;
grant select on table analytics.chart_customer_patients to authenticated;

alter table if exists analytics.chart_customer_master enable row level security;
alter table if exists analytics.chart_customer_patients enable row level security;

drop policy if exists "chart_patient_master_select_assigned_hospitals" on analytics.chart_customer_master;
drop policy if exists "chart_customer_master_select_assigned_hospitals" on analytics.chart_customer_master;
create policy "chart_customer_master_select_assigned_hospitals"
  on analytics.chart_customer_master
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_customer_master.hospital_id
        )
    )
  );

drop policy if exists "chart_customer_patients_select_assigned_hospitals" on analytics.chart_customer_patients;
create policy "chart_customer_patients_select_assigned_hospitals"
  on analytics.chart_customer_patients
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_customer_patients.hospital_id
        )
    )
  );

create or replace view analytics.chart_kpis_period_view as
select
  date_trunc('week', metric_date)::date as period_start_date,
  'week'::text as period_type,
  hospital_id,
  chart_type,
  sum(sales_amount) as sales_amount,
  sum(visit_count) as visit_count,
  sum(new_customer_count) as new_customer_count
from analytics.chart_daily_kpis
group by 1, 2, 3, 4
union all
select
  date_trunc('month', metric_date)::date as period_start_date,
  'month'::text as period_type,
  hospital_id,
  chart_type,
  sum(sales_amount) as sales_amount,
  sum(visit_count) as visit_count,
  sum(new_customer_count) as new_customer_count
from analytics.chart_daily_kpis
group by 1, 2, 3, 4
union all
select
  metric_date as period_start_date,
  'day'::text as period_type,
  hospital_id,
  chart_type,
  sales_amount,
  visit_count,
  new_customer_count
from analytics.chart_daily_kpis;

grant select on table analytics.chart_kpis_period_view to authenticated, service_role;
