-- eFriends identity resolution using owner name + patient set similarity.
-- Purpose: reduce homonym collisions when customer id is absent.

create extension if not exists pgcrypto;

create table if not exists analytics.chart_customer_identity_map (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  owner_name_norm text not null,
  customer_key_norm text not null,
  patient_names text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, chart_type, owner_name_norm, customer_key_norm)
);

create index if not exists idx_chart_customer_identity_map_owner
  on analytics.chart_customer_identity_map (hospital_id, chart_type, owner_name_norm);

drop trigger if exists trg_chart_customer_identity_map_updated_at on analytics.chart_customer_identity_map;
create trigger trg_chart_customer_identity_map_updated_at
  before update on analytics.chart_customer_identity_map
  for each row
  execute function analytics.chart_touch_updated_at();

grant select, insert, update, delete on table analytics.chart_customer_identity_map to service_role;
grant select on table analytics.chart_customer_identity_map to authenticated;

alter table analytics.chart_customer_identity_map enable row level security;

drop policy if exists "chart_customer_identity_map_select_assigned_hospitals" on analytics.chart_customer_identity_map;
create policy "chart_customer_identity_map_select_assigned_hospitals"
  on analytics.chart_customer_identity_map
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_customer_identity_map.hospital_id
        )
    )
  );

create or replace function analytics.norm_owner_name(input text)
returns text
language sql
immutable
as $$
  select lower(trim(regexp_replace(coalesce(input,''), '\s+', ' ', 'g')));
$$;

create or replace function analytics.parse_patient_names(input text)
returns text[]
language sql
immutable
as $$
  select coalesce(
    array(
      select distinct lower(trim(regexp_replace(x, '\s+', ' ', 'g')))
      from unnest(string_to_array(coalesce(input,''), ',')) as x
      where trim(x) <> ''
      order by 1
    ),
    '{}'::text[]
  );
$$;

create or replace function analytics.jaccard_similarity(a text[], b text[])
returns numeric
language sql
immutable
as $$
  with
  a0 as (
    select distinct x as v from unnest(coalesce(a,'{}'::text[])) x where x is not null and x <> ''
  ),
  b0 as (
    select distinct x as v from unnest(coalesce(b,'{}'::text[])) x where x is not null and x <> ''
  ),
  inter as (
    select count(*)::numeric as c from a0 join b0 using (v)
  ),
  uni as (
    select count(*)::numeric as c from (select v from a0 union select v from b0) u
  )
  select case when (select c from uni) = 0 then 0 else (select c from inter) / (select c from uni) end;
$$;
