-- Chart KPI ingestion foundation (IntoVet first).

create table if not exists analytics.chart_upload_runs (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  source_file_name text not null,
  source_file_hash text not null,
  status text not null default 'pending',
  total_rows integer not null default 0,
  imported_rows integer not null default 0,
  skipped_rows integer not null default 0,
  error_rows integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  unique (hospital_id, chart_type, source_file_hash)
);

create index if not exists idx_chart_upload_runs_hospital_started_at
  on analytics.chart_upload_runs (hospital_id, started_at desc);

create table if not exists analytics.chart_transactions_raw (
  id bigint generated by default as identity primary key,
  run_id bigint references analytics.chart_upload_runs(id) on delete set null,
  hospital_id text not null,
  chart_type text not null,
  source_file_name text not null,
  source_file_hash text not null,
  source_row_no integer not null,
  row_signature text not null,
  service_date date not null,
  customer_no_raw text,
  customer_name_raw text,
  patient_name_raw text,
  final_amount_raw numeric not null default 0,
  customer_key_norm text not null,
  patient_key_norm text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  unique (hospital_id, chart_type, source_file_hash, source_row_no),
  unique (hospital_id, chart_type, row_signature)
);

create index if not exists idx_chart_transactions_raw_hospital_service_date
  on analytics.chart_transactions_raw (hospital_id, service_date desc);

create index if not exists idx_chart_transactions_raw_patient_key
  on analytics.chart_transactions_raw (hospital_id, chart_type, patient_key_norm);

create table if not exists analytics.chart_customer_master (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  customer_key_norm text not null,
  customer_no_raw_latest text,
  customer_name_latest text,
  first_visit_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, chart_type, customer_key_norm)
);

create index if not exists idx_chart_customer_master_first_visit
  on analytics.chart_customer_master (hospital_id, chart_type, first_visit_date desc);

create table if not exists analytics.chart_customer_patients (
  id bigint generated by default as identity primary key,
  hospital_id text not null,
  chart_type text not null,
  customer_key_norm text not null,
  patient_key_norm text not null,
  patient_name_latest text,
  first_seen_date date not null,
  last_seen_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, chart_type, customer_key_norm, patient_key_norm)
);

create index if not exists idx_chart_customer_patients_customer
  on analytics.chart_customer_patients (hospital_id, chart_type, customer_key_norm);

create table if not exists analytics.chart_daily_kpis (
  metric_date date not null,
  hospital_id text not null,
  chart_type text not null,
  sales_amount numeric not null default 0,
  visit_count integer not null default 0,
  new_customer_count integer not null default 0,
  source_run_id bigint references analytics.chart_upload_runs(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (metric_date, hospital_id, chart_type)
);

create index if not exists idx_chart_daily_kpis_hospital_metric_date
  on analytics.chart_daily_kpis (hospital_id, metric_date desc);

create table if not exists analytics.chart_upload_errors (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analytics.chart_upload_runs(id) on delete cascade,
  hospital_id text not null,
  chart_type text not null,
  source_row_no integer,
  error_code text,
  error_message text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_chart_upload_errors_run
  on analytics.chart_upload_errors (run_id, created_at desc);

create or replace function analytics.chart_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_chart_customer_master_updated_at on analytics.chart_customer_master;
create trigger trg_chart_customer_master_updated_at
  before update on analytics.chart_customer_master
  for each row
  execute function analytics.chart_touch_updated_at();

drop trigger if exists trg_chart_customer_patients_updated_at on analytics.chart_customer_patients;
create trigger trg_chart_customer_patients_updated_at
  before update on analytics.chart_customer_patients
  for each row
  execute function analytics.chart_touch_updated_at();

drop trigger if exists trg_chart_daily_kpis_updated_at on analytics.chart_daily_kpis;
create trigger trg_chart_daily_kpis_updated_at
  before update on analytics.chart_daily_kpis
  for each row
  execute function analytics.chart_touch_updated_at();

grant select, insert, update, delete on table analytics.chart_upload_runs to service_role;
grant select, insert, update, delete on table analytics.chart_transactions_raw to service_role;
grant select, insert, update, delete on table analytics.chart_customer_master to service_role;
grant select, insert, update, delete on table analytics.chart_customer_patients to service_role;
grant select, insert, update, delete on table analytics.chart_daily_kpis to service_role;
grant select, insert, update, delete on table analytics.chart_upload_errors to service_role;

grant select on table analytics.chart_daily_kpis to authenticated;
grant select on table analytics.chart_customer_master to authenticated;
grant select on table analytics.chart_customer_patients to authenticated;

alter table analytics.chart_upload_runs enable row level security;
alter table analytics.chart_transactions_raw enable row level security;
alter table analytics.chart_customer_master enable row level security;
alter table analytics.chart_customer_patients enable row level security;
alter table analytics.chart_daily_kpis enable row level security;
alter table analytics.chart_upload_errors enable row level security;

drop policy if exists "chart_daily_kpis_select_assigned_hospitals" on analytics.chart_daily_kpis;
create policy "chart_daily_kpis_select_assigned_hospitals"
  on analytics.chart_daily_kpis
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_daily_kpis.hospital_id
        )
    )
  );

drop policy if exists "chart_customer_master_select_assigned_hospitals" on analytics.chart_customer_master;
create policy "chart_customer_master_select_assigned_hospitals"
  on analytics.chart_customer_master
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_customer_master.hospital_id
        )
    )
  );

drop policy if exists "chart_customer_patients_select_assigned_hospitals" on analytics.chart_customer_patients;
create policy "chart_customer_patients_select_assigned_hospitals"
  on analytics.chart_customer_patients
  for select
  to authenticated
  using (
    exists (
      select 1
      from core.users u
      where u.id::text = auth.uid()::text
        and (
          lower(coalesce(u.role, 'member')) = 'admin'
          or u.hospital_id = chart_customer_patients.hospital_id
        )
    )
  );

create or replace view analytics.chart_kpis_period_view as
select
  date_trunc('week', metric_date)::date as period_start_date,
  'week'::text as period_type,
  hospital_id,
  chart_type,
  sum(sales_amount) as sales_amount,
  sum(visit_count) as visit_count,
  sum(new_customer_count) as new_customer_count
from analytics.chart_daily_kpis
group by 1, 2, 3, 4
union all
select
  date_trunc('month', metric_date)::date as period_start_date,
  'month'::text as period_type,
  hospital_id,
  chart_type,
  sum(sales_amount) as sales_amount,
  sum(visit_count) as visit_count,
  sum(new_customer_count) as new_customer_count
from analytics.chart_daily_kpis
group by 1, 2, 3, 4
union all
select
  metric_date as period_start_date,
  'day'::text as period_type,
  hospital_id,
  chart_type,
  sales_amount,
  visit_count,
  new_customer_count
from analytics.chart_daily_kpis;

grant select on table analytics.chart_kpis_period_view to authenticated, service_role;
